"""Generate docs/data.js — inlines the example datasets for the web demo.

    python scripts/build_demo_data.py

The interactive demo page (docs/) is fully self-contained: it runs a
JavaScript port of the engine against the SAME datasets as the Python
demos, inlined here so the page works from file:// and GitHub Pages alike.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).parents[1]


def main() -> None:
    products = json.loads((ROOT / "examples/search_demo/products.json").read_text(encoding="utf-8"))
    labelset = json.loads((ROOT / "examples/search_demo/labelset.json").read_text(encoding="utf-8"))
    golden = json.loads(
        (ROOT / "examples/search_demo/golden/search_eval_baseline.json").read_text(encoding="utf-8")
    )
    corpus = json.loads((ROOT / "examples/citation_demo/corpus.json").read_text(encoding="utf-8"))
    citations = json.loads((ROOT / "examples/citation_demo/citations.json").read_text(encoding="utf-8"))

    def js(name: str, value: object) -> str:
        return f"const {name} = {json.dumps(value, ensure_ascii=False, indent=2)};\n"

    out = (
        "// Generated by scripts/build_demo_data.py — do not edit by hand.\n"
        "// Same datasets as the Python demos (examples/), inlined for the web demo.\n"
        + js("PRODUCTS", products)
        + js("LABELSET", labelset)
        + js("GOLDEN_BASELINE", golden)
        + js("CORPUS_DATA", corpus)
        + js("CITATIONS_DATA", citations)
        + "if (typeof module !== 'undefined') module.exports = "
        "{ PRODUCTS, LABELSET, GOLDEN_BASELINE, CORPUS_DATA, CITATIONS_DATA };\n"
    )
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs/data.js").write_text(out, encoding="utf-8")
    print("wrote docs/data.js")


if __name__ == "__main__":
    main()
